# install.ps1 — one-shot setup for eidetic on Windows
# Usage: right-click > Run with PowerShell, or: powershell -ExecutionPolicy Bypass -File install.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step($msg) { Write-Host "`n>> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "   $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "   $msg" -ForegroundColor Yellow }
function Write-Err($msg)  { Write-Host "   $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "  eidetic installer" -ForegroundColor White
Write-Host "  =================" -ForegroundColor DarkGray
Write-Host ""

# ── 1. Check prerequisites ──────────────────────────────────────────

Write-Step "Checking prerequisites"

# Node.js
try {
    $nodeVersion = (node --version 2>&1).ToString().Trim()
    Write-Ok "Node.js $nodeVersion"
} catch {
    Write-Err "Node.js not found. Install it from https://nodejs.org"
    exit 1
}

# Python
$python = $null
foreach ($cmd in "python", "python3") {
    try {
        $pyVer = (& $cmd --version 2>&1).ToString().Trim()
        $python = $cmd
        Write-Ok "$pyVer ($cmd)"
        break
    } catch {}
}
if (-not $python) {
    Write-Err "Python not found. Install it from https://python.org"
    exit 1
}

# Ollama
try {
    $ollamaHelp = ollama --version 2>&1
    Write-Ok "Ollama found"
} catch {
    Write-Err "Ollama not found. Install it from https://ollama.com"
    exit 1
}

# ── 2. Install Node dependencies ────────────────────────────────────

Write-Step "Installing Node dependencies"
npm install
if ($LASTEXITCODE -ne 0) { Write-Err "npm install failed"; exit 1 }
Write-Ok "Done"

# ── 3. Install Python dependencies ──────────────────────────────────

Write-Step "Installing Python dependencies"
& $python -m pip install -r ingestion/requirements.txt
if ($LASTEXITCODE -ne 0) { Write-Err "pip install failed"; exit 1 }
Write-Ok "Done"

# ── 4. Choose Ollama model based on VRAM ────────────────────────────

Write-Step "Choosing LLM model"
Write-Host ""
Write-Host "   How much GPU VRAM do you have?" -ForegroundColor White
Write-Host ""
Write-Host "   [1] 8 GB or less    (laptop / budget GPU)      -> gemma4:e4b" -ForegroundColor DarkGray
Write-Host "   [2] 12-16 GB        (RTX 4070, 5060 Ti, etc.)  -> gemma4:26b" -ForegroundColor DarkGray
Write-Host "   [3] 24-32 GB        (RTX 4090, 5090, etc.)     -> gemma4:31b" -ForegroundColor DarkGray
Write-Host ""

do {
    $choice = Read-Host "   Enter 1, 2, or 3"
} while ($choice -notin "1", "2", "3")

switch ($choice) {
    "1" { $model = "gemma4:e4b"; $label = "gemma4:e4b (edge 4B)" }
    "2" { $model = "gemma4:26b"; $label = "gemma4:26b (26B MoE)" }
    "3" { $model = "gemma4:31b"; $label = "gemma4:31b (31B dense)" }
}

Write-Ok "Selected: $label"

# ── 5. Pull models ──────────────────────────────────────────────────

Write-Step "Pulling $model (this may take a while)"
ollama pull $model
if ($LASTEXITCODE -ne 0) { Write-Err "Failed to pull $model"; exit 1 }
Write-Ok "$model ready"

Write-Step "Pulling embedding model (nomic-embed-text)"
ollama pull nomic-embed-text
if ($LASTEXITCODE -ne 0) { Write-Err "Failed to pull nomic-embed-text"; exit 1 }
Write-Ok "nomic-embed-text ready"

# ── 6. Generate secrets & write .env.local ──────────────────────────

Write-Step "Generating configuration"

$envFile = Join-Path $PSScriptRoot ".env.local"

# Generate a random 32-byte hex secret
$bytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
$authSecret = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""

$envContent = @"
# Generated by install.ps1
AUTH_SECRET=$authSecret
OLLAMA_MODEL=$model
"@

Set-Content -Path $envFile -Value $envContent -Encoding UTF8
Write-Ok ".env.local written"

# ── 7. Build ────────────────────────────────────────────────────────

Write-Step "Building eidetic (production)"
npm run build
if ($LASTEXITCODE -ne 0) { Write-Err "Build failed"; exit 1 }
Write-Ok "Build complete"

# ── Done ────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "  ==============================================" -ForegroundColor DarkGray
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  To start eidetic:" -ForegroundColor White
Write-Host "    npm start" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Then open http://localhost:3000 in your browser." -ForegroundColor White
Write-Host "  You'll be asked to set a password on first visit." -ForegroundColor White
Write-Host "  ==============================================" -ForegroundColor DarkGray
Write-Host ""
